from typing import Protocol
from uuid import UUID

from api.domain.entities.household_invite import HouseholdInvite


class HouseholdInviteRepository(Protocol):
    async def create(self, invite: HouseholdInvite) -> HouseholdInvite: ...

    async def get_by_id(self, invite_id: UUID) -> HouseholdInvite | None: ...

    async def get_pending_by_email(self, email: str) -> HouseholdInvite | None: ...

    async def list_by_household(self, household_id: UUID) -> list[HouseholdInvite]: ...

    async def mark_accepted(self, invite_id: UUID) -> None: ...

    async def cancel(self, invite_id: UUID) -> None: ...
